export const USER_NOT_FOUND = "user-not-found";
export const USER_ALREADY_REGISTERED = "user-already-registered";

export const category = [
    "Corte",
    "Hotel",
    "Maquiagem",
    "Pintura",
    "Medicina",
    "Pet-Shop",
    "Outros",
];

export const weekDays = [
    "Domingo",
    "Segunda-Feira",
    "Terça-Feira",
    "Quarta-Feira",
    "Quinta-Feira",
    "Sexta-Feira",
    "Sábado",
];

export const dummyStores = [
    {
        image: "/cabeleleila_leila.png",
        name: "Cabeleleila Leila",
        category: ["Corte", "Pintura", "Maquiagem"],
        description:
            "Venha se renovar conosco! Valores competitivos e resultados indiscutíveis!",
        workDays: [
            "Segunda-Feira",
            "Terça-Feira",
            "Quarta-Feira",
            "Quinta-Feira",
            "Sexta-Feira",
            "Sábado",
        ],
        startTime: "08:00",
        endTime: "17:00",
        street: 'Rua da Imprensa',
        homeNumber: '137',
        neighborhood: 'Monte Castelo',
        state: 'MG',
        city: "Belo Horizonte",
    },
    {
        image: "/cabeleleila_leila.png",
        name: "Cabeleleila Leila",
        category: ["Corte", "Pintura", "Maquiagem"],
        description:
            "Venha se renovar conosco! Valores competitivos e resultados indiscutíveis!",
        workDays: [
            "Segunda-Feira",
            "Terça-Feira",
            "Quarta-Feira",
            "Quinta-Feira",
            "Sexta-Feira",
            "Sábado",
        ],
        startTime: "08:00",
        endTime: "17:00",
        street: 'Rua da Imprensa',
        homeNumber: '137',
        neighborhood: 'Monte Castelo',
        state: 'MG',
        city: "Belo Horizonte",
    },
    {
        image: "/cabeleleila_leila.png",
        name: "Cabeleleila Leila",
        category: ["Corte", "Pintura", "Maquiagem"],
        description:
            "Venha se renovar conosco! Valores competitivos e resultados indiscutíveis!",
        workDays: [
            "Segunda-Feira",
            "Terça-Feira",
            "Quarta-Feira",
            "Quinta-Feira",
            "Sexta-Feira",
            "Sábado",
        ],
        startTime: "08:00",
        endTime: "17:00",
        street: 'Rua da Imprensa',
        homeNumber: '137',
        neighborhood: 'Monte Castelo',
        state: 'MG',
        city: "Belo Horizonte",
    },
    {
        image: "/cabeleleila_leila.png",
        name: "Cabeleleila Leila",
        category: ["Corte", "Pintura", "Maquiagem"],
        description:
            "Venha se renovar conosco! Valores competitivos e resultados indiscutíveis!",
        workDays: [
            "Segunda-Feira",
            "Terça-Feira",
            "Quarta-Feira",
            "Quinta-Feira",
            "Sexta-Feira",
            "Sábado",
        ],
        startTime: "08:00",
        endTime: "17:00",
        street: 'Rua da Imprensa',
        homeNumber: '137',
        neighborhood: 'Monte Castelo',
        state: 'MG',
        city: "Belo Horizonte",
    },
    {
        image: "/cabeleleila_leila.png",
        name: "Cabeleleila Leila",
        category: ["Corte", "Pintura", "Maquiagem"],
        description:
            "Venha se renovar conosco! Valores competitivos e resultados indiscutíveis!",
        workDays: [
            "Segunda-Feira",
            "Terça-Feira",
            "Quarta-Feira",
            "Quinta-Feira",
            "Sexta-Feira",
            "Sábado",
        ],
        startTime: "08:00",
        endTime: "17:00",
        street: 'Rua da Imprensa',
        homeNumber: '137',
        neighborhood: 'Monte Castelo',
        state: 'MG',
        city: "Belo Horizonte",
    },
    {
        image: "/cabeleleila_leila.png",
        name: "Cabeleleila Leila",
        category: ["Corte", "Pintura", "Maquiagem"],
        description:
            "Venha se renovar conosco! Valores competitivos e resultados indiscutíveis!",
        workDays: [
            "Segunda-Feira",
            "Terça-Feira",
            "Quarta-Feira",
            "Quinta-Feira",
            "Sexta-Feira",
            "Sábado",
        ],
        startTime: "08:00",
        endTime: "17:00",
        street: 'Rua da Imprensa',
        homeNumber: '137',
        neighborhood: 'Monte Castelo',
        state: 'MG',
        city: "Belo Horizonte",
    },
];
